import './sum.test.js'
import './isBoolean.test.js'
import './isArray.test.js'
import './nth.test.js'
import './parseUrl.test.js'
import './throttle.test.js'
import './isString.test.js'
import './debounce.test.js'
